### ISSUE TITLE
I should stop trolling friends' repos :(

### ISSUE THREAD

**Issue by eddie-dunn** [olof/debian-svtplay-dl#1]
hi i cant run the debian-stvpaly-dl

i clock setyp.py but notinh happens.

help plz

**Comment by olof** [comment]
Hi @eddie-dunn, as an experienced linux engineer, I would expected you to know how to extract the python file from the ar archive and run it.

**Comment by eddie-dunn** [comment]
i am not experiences linus engineer. where is teh ar file in ur repo?

**Comment by olof** [comment]
no, you're right, my bad. you'd have to build it first: `debuild` and then you'd get a .deb. A .deb is an AR archive, which you can extract. But you could take the program [directly from upstream](https://github.com/spaam/svtplay-dl/raw/master/svtplay-dl) instead, since this repository is primarily aimed towards Debian/Ubuntu users, rather than Windows users. Hope this helps. Good luck :-)
